[build]
  command = "pnpm run build"
  publish = ".next"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

  [[redirects]]
  from = "/favicon.ico"
  to = "/favicon.ico"
  status = 200

[[redirects]]
  from = "/saltcrm-logo.png"
  to = "/saltcrm-logo.png"
  status = 200

[[redirects]]
  from = "/screenshot.png"
  to = "/screenshot.png"
  status = 200


[build.environment]
  NODE_VERSION = "18"